// Neutral Milk Hotel archive data
// Source: neutralmilkhotel.org (song index + bootography), scraped 2026-09-08.
// To add a song: push {title, type, aka, alt, credit, unconfirmed} onto NMH_SONGS.
//   type: album | single | demo | live | compilation | alt. title | mislabel
//   (tracks by other bands are excluded; covers NMH played live stay, typed 'live')
// To add a recording: push a show object onto NMH_SHOWS.
//   {date:'YYYY-MM-DD', year, venue, city, format, source, quality, length,
//    lineage, no_recording:false, notes, setlist:[], links:[{url,text}]}
// links: recordings only -- youtube.com / youtu.be / archive.org.
// Anything else is filtered out at render time by isRecordingLink().

const NMH_SONGS = [
 {
  "title": "A Baby for Pree",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "A&E Melody",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Acid",
  "type": "live",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Angel Eyes",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": true
 },
 {
  "title": "All the Colors of the Rainbow",
  "type": "live",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "April 1st",
  "type": "demo",
  "aka": null,
  "alt": "Swallowed",
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "April 8th",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Arms So Real",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Aunt Eggma Blowtorch",
  "type": "single",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Avery Island / April 1st",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Beautiful Baby",
  "type": "mislabel",
  "aka": "Rubby Bulbs",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Beautiful Face",
  "type": "alt. title",
  "aka": "In The Aeroplane Over The Sea",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Biscuit",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Bomb Drop",
  "type": "alt. title",
  "aka": "Rubby Bulbs",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Bucket",
  "type": "compilation",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Calypso Part One",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Calypso Part Two",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Candy Coated Dream",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Carnival",
  "type": "alt. title",
  "aka": "untitled [",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Charlotte",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Chocolate Coffin",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Circle of Friends",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Communist Daughter",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Conversation with Rob Schneider",
  "type": "mislabel",
  "aka": "Conversation with Will Hart",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Conversation with Will Hart",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Digestion Machine",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Engine",
  "type": "compilation",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Everything Is",
  "type": "single",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Ferris Wheel on Fire",
  "type": "live",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Follow Me Down",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": true
 },
 {
  "title": "Gardenhead / Leave Me Alone",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Ghost",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Glow Into You",
  "type": "alt. title",
  "aka": "Where You'll Find Me Now",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Glue",
  "type": "compilation",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Going Down",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Goldaline",
  "type": "live",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Golden Leaf",
  "type": "mislabel",
  "aka": "Goldaline",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Heroin Bag",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": true
 },
 {
  "title": "Holland, 1945",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Hypnotic Sounds",
  "type": "alt. title",
  "aka": "Aunt Eggma Blowtorch",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "I Bring Jennifer",
  "type": "alt. title",
  "aka": "Jennifer",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "I Hear You Breathe",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "I Love How You Love Me",
  "type": "live",
  "aka": null,
  "alt": null,
  "credit": "Phil Spector cover",
  "unconfirmed": false
 },
 {
  "title": "I Will Bury You in Time",
  "type": "live",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "In the Aeroplane Over the Sea",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Invent Yourself a Shortcake",
  "type": "compilation",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Jaw Harp",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Jennifer",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Jesus Christ",
  "type": "alt. title",
  "aka": "King of Carrot Flowers Pt. 2",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "King of Carrot Flowers Pt. 1",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "King of Carrot Flowers Pt. 2",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "King of Carrot Flowers Pt. 3",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Life Is Neverending",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": true
 },
 {
  "title": "Little Birds",
  "type": "live",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Los Angeles",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Los Angelos Car Song",
  "type": "alt. title",
  "aka": "Los Angeles",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Love You More Than Life",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Love You on a Tuesday",
  "type": "mislabel",
  "aka": "Tuesday Moon",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Marching Theme",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Message Sent",
  "type": "demo",
  "aka": null,
  "alt": "Through My Tears",
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Mother",
  "type": "live",
  "aka": null,
  "alt": null,
  "credit": "John Lennon",
  "unconfirmed": false
 },
 {
  "title": "More Noise",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "My Dream Girl Don't Exist",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "My Dreamgirl",
  "type": "alt. title",
  "aka": "My Dream Girl Don't Exist",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "My Skull",
  "type": "live",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Naomi",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Noisy Racket",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Nothing's Going To Happen",
  "type": "live",
  "aka": null,
  "alt": null,
  "credit": "Tall Dwarfs",
  "unconfirmed": false
 },
 {
  "title": "Now I'm Going Down",
  "type": "mislabel",
  "aka": "Going Down",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Now There is Nothing",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": true
 },
 {
  "title": "Oh Comely",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Oh Sister",
  "type": "live",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Piggy",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Prank Call",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Preacherman",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Pree-Sisters Swallowing a Donkey's Eye",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Rain",
  "type": "live",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Random Noise",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Random Noise II",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Random Noise III",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Rubby Bulbs",
  "type": "compilation",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Sailing Through",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "She Did A Lot of Acid",
  "type": "alt. title",
  "aka": "Acid",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Sinking Ship",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Snow Song, Pt. 1",
  "type": "single",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Someone Is Waiting",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Song Against Sex",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Song for Ché",
  "type": "live",
  "aka": null,
  "alt": null,
  "credit": "Charlie Haden cover",
  "unconfirmed": false
 },
 {
  "title": "Spooky Sounds",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Swallowed",
  "type": "alt. title",
  "aka": "April 1st",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Sweet Marie",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Swimming in your Speakers",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": true
 },
 {
  "title": "Synthetic Flying Machine",
  "type": "alt. title",
  "aka": "King of Carrot Flowers Pt. 3",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Tea Time",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "The Fool",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "The Gifted Children - \"Neutral Milk Hotel\"",
  "type": "mislabel",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "The Penny Arcade In California",
  "type": "alt. title",
  "aka": "untitled [",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Three Peaches",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Through My Tears",
  "type": "alt. title / mislabel",
  "aka": "Message Sent",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Tuesday Moon",
  "type": "single",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Two-Headed Boy",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Two-Headed Boy Pt. 2",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "untitled (\"Ghost\" coda)",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "untitled (Ptolemaic Terrascope No. 21)",
  "type": "compilation",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Up And Over",
  "type": "alt. title",
  "aka": "King of Carrot Flowers Pt. 3",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Up And Over We Go",
  "type": "alt. title",
  "aka": "King of Carrot Flowers Pt. 3",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Where You'll Find Me Now",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Wishful Eyes",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Wood Guitar",
  "type": "demo",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Worms In The Wind",
  "type": "live",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "Worms",
  "type": "alt. title",
  "aka": "Worms In The Wind",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "You Can Deny All Your Addictions",
  "type": "mislabel",
  "aka": "A&E Melody",
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "You've Passed",
  "type": "album",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": false
 },
 {
  "title": "You've Passed Pt. 2",
  "type": "live",
  "aka": null,
  "alt": null,
  "credit": null,
  "unconfirmed": true
 }
];

const NMH_SHOWS = [
 {
  "date": "1996-07-04",
  "year": 1996,
  "venue": "Aquarius Records",
  "city": "San Francisco, CA",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "32min",
  "lineage": null,
  "no_recording": false,
  "notes": "Earliest known live Neutral Milk Hotel recording. Great acoustic set by Jeff, with a few rarely played songs, including the only known live version of \"My Dreamgirl Don't Exist\". This bootleg is very common, and mp3s of it can easily be found online. Most mp3 versions cut out some between-song chatter, however, such as when Jeff mentions that the first song is actually two songs: one called \"Oh Comely\" and another called \"Goldaline\".\nThe unknown song (\"swimming in your speakers\") seems to be a sister song to \"Snow Song Pt. 1\".. maybe it's \"Snow Song Pt. 2\"?",
  "setlist": [
   "Oh Comely",
   "Engine",
   "Oh Sister",
   "My Dreamgirl Don't Exist",
   "Sailing Through",
   "Acid / Ruby Bulbs / unknown (\"swimming in your speakers\")"
  ],
  "links": []
 },
 {
  "date": "1996-07-06",
  "year": 1996,
  "venue": "The Backstage",
  "city": "Seattle, WA",
  "format": "audio",
  "source": "audience",
  "quality": "ok",
  "length": "32min",
  "lineage": null,
  "no_recording": false,
  "notes": "This show popped up on Soulseek in early '05. The sound is decent most of the time, but it skips a lot on tracks 4 through 8. \"The Fool\" was mislabeled as \"Message Sent\", but on the recording itself, it appears Jeff refers to the \"Through My Tears\" conglomeration by that title.",
  "setlist": [
   "Song Against Sex",
   "A Baby for Pree",
   "Gardenhead / Leave Me Alone",
   "Tuesday Moon",
   "Message Sent (Through My Tears / Goldaline / unknown [\"now there is nothing\"])",
   "The Fool",
   "Naomi",
   "Ruby Bulbs",
   "King of Carrot Flowers Pts 2 and 3",
   "Ferris Wheel on Fire",
   "Everything Is"
  ],
  "links": []
 },
 {
  "date": "1996-07-07",
  "year": 1996,
  "venue": "EJ's",
  "city": "Portland, OR",
  "format": "video",
  "source": "audience",
  "quality": "good",
  "length": "?",
  "lineage": null,
  "no_recording": false,
  "notes": "Three videos from this show have been put on YouTube. The filmer has said that he didn't record the entire set, however. Gardenhead/Leave Me Alone\nSnow Song / King of Carrot Flowers Pt. 3\nRuby Bulbs / Someone Is Waiting",
  "setlist": [],
  "links": [
   {
    "url": "http://www.youtube.com/watch?v=hFiKG9UzhoE",
    "text": "Gardenhead/Leave Me Alone"
   },
   {
    "url": "http://www.youtube.com/watch?v=UcWQEdidjIg",
    "text": "Snow Song / King of Carrot Flowers Pt. 3"
   },
   {
    "url": "http://www.youtube.com/watch?v=RVEm1_KOGIU",
    "text": "Ruby Bulbs / Someone Is Waiting"
   }
  ]
 },
 {
  "date": "1996-07-17",
  "year": 1996,
  "venue": "Knitting Factory",
  "city": "New York, NY",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "39m source: wm-d3 pro-walkman (analog cassette) and ecm 909a mics.",
  "lineage": "taped by chris r. (XLII-S master) transfer: master cassette> Sony K707ES> tascamUS-428> sound forge4.5> cdwav> flac by ronnie from chicago",
  "no_recording": false,
  "notes": "Another old show that took a decade to make it into circulation (Sept '05). Features an unreleased song called \"Arms So Real\" which isn't available on any other known live recording.",
  "setlist": [
   "Song Against Sex",
   "Gardenhead / Leave Me Alone",
   "Tuesday Moon",
   "Arms So Real",
   "A Baby For Pree",
   "The Fool",
   "Everything Is",
   "Naomi",
   "Snow Song Pt. 1",
   "King of Carrot Flowers Pts 2 and 3",
   "(encore break / tuning)",
   "Message Sent"
  ],
  "links": []
 },
 {
  "date": "1996-07-22",
  "year": 1996,
  "venue": "Oakland Beehive",
  "city": "Pittsburg, PA",
  "format": "audio",
  "source": "audience",
  "quality": "poor",
  "length": "34m",
  "lineage": null,
  "no_recording": false,
  "notes": "NMH jammed with the opening band, Butterglory, for a warm up.. sounds kinda like an old blues song or something.",
  "setlist": [
   "jam with Butterglory",
   "Gardenhead / Leave Me Alone",
   "Tuesday Moon",
   "A Baby For Pree",
   "Naomi",
   "Everything Is",
   "The Fool",
   "Snow Song Pt. 1",
   "King of Carrot Flowers Pts. 2 and 3"
  ],
  "links": []
 },
 {
  "date": "1996-07-23",
  "year": 1996,
  "venue": "Sudsy Malone's",
  "city": "Cincinnati, OH",
  "format": "audio",
  "source": "audience",
  "quality": "ok",
  "length": "43min",
  "lineage": null,
  "no_recording": false,
  "notes": "Includes a rare live performance of \"You've Passed\", which is paired with another, unknown song. Perhaps it's part of \"You've Passed\" that was cut from the album version?\nThe show's other unknown song (\"now there is nothing\") is the third section of \"Message Sent\" and seems to be a sister song to \"Oh Sister\".",
  "setlist": [
   "King Of Carrot Flowers Pts. 2 and 3",
   "Gardenhead / Leave Me Alone",
   "Tuesday Moon",
   "You've Passed / unknown (\"You've Passed Pt 2\"?)",
   "Everything Is",
   "Ruby Bulbs",
   "Naomi",
   "Ferris Wheel On Fire",
   "Message Sent (Through My Tears / Goldaline)",
   "Message Sent [cont.] (\"now there is nothing\")",
   "Snow Song Pt. 1"
  ],
  "links": []
 },
 {
  "date": "1996-07-25",
  "year": 1996,
  "venue": "Cicero's",
  "city": "St. Louis, MO",
  "format": "audio",
  "source": "soundboard",
  "quality": "ok",
  "length": "40m",
  "lineage": null,
  "no_recording": false,
  "notes": "Soundboard recording, but not the best quality. A lot of tape hiss.",
  "setlist": [
   "Song Against Sex",
   "Gardenhead / Leave Me Alone",
   "Tuesday Moon",
   "A Baby For Pree",
   "The Fool",
   "Message Sent (Through My Tears / Goldaline)",
   "Message Sent [cont.] (\"now there is nothing\")",
   "Everything Is",
   "Ferris Wheel on Fire",
   "Naomi",
   "Snow Song pt 1",
   "King of Carrot Flowers parts 2 & 3"
  ],
  "links": []
 },
 {
  "date": "1996-08-01",
  "year": 1996,
  "venue": "Knitting Factory",
  "city": "New York, NY",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "54m source: wm-d3 pro-walkman (analog cassette) and ecm 909a mics.",
  "lineage": "taped by chris r. (XLII-S master) transfer: master cassette> Sony K707ES> tascamUS-428> sound forge4.5> cdwav> flac by ronnie from chicago",
  "no_recording": false,
  "notes": "Another old show that took a long time to surface (Sept '05). Features a rare live recording of \"Bucket\". Like most pre-Aeroplane versions, \"Oh Comely\" has some slightly altered lyrics, and doesn't have the \"Goldaline\" ending (\"Goldaline\" is included in the last song, \"Message Sent,\" however.)",
  "setlist": [
   "Oh Comely",
   "Bucket",
   "Song Against Sex",
   "A Baby For Pree",
   "King Of Carrot Flowers Pt. 3",
   "Tuesday Moon / circus music jam",
   "Engine",
   "Naomi",
   "Ferris Wheel On Fire",
   "Gardenhead / Leave Me Alone",
   "Snow Song Pt. 1",
   "Everything Is",
   "Message Sent (Through My Tears/Goldaline/unknown [\"now there is nothing\"])"
  ],
  "links": []
 },
 {
  "date": "1996-09-06",
  "year": 1996,
  "venue": "CMJ Mergefest, Westbeth Theatre",
  "city": "New York, NY",
  "format": null,
  "source": null,
  "quality": null,
  "length": null,
  "lineage": null,
  "no_recording": true,
  "notes": "",
  "setlist": [
   "A Baby For Pree",
   "Gardenhead / Leave Me Alone",
   "Tuesday Moon",
   "Ferris Wheel On Fire",
   "Naomi",
   "Ruby Bulbs",
   "Snow Song",
   "(the setlist says \"trilogy\" here.. I'm assuming Message Sent)",
   "King of Carrot Flowers Pt 3"
  ],
  "links": []
 },
 {
  "date": "1996-10-05",
  "year": 1996,
  "venue": "Other Music",
  "city": "New York, NY",
  "format": "audio",
  "source": "audience",
  "quality": "ok",
  "length": "33m",
  "lineage": null,
  "no_recording": false,
  "notes": "Jeff Mangum acoustic in-store performance. \"Two Headed Boy\" is an early version with several slightly different lyrics. Also, this recording features a rare live performance of \"April 8th\".",
  "setlist": [
   "Two-Headed Boy",
   "Naomi",
   "April 8th",
   "I Will Bury You In Time",
   "Engine",
   "Everything Is",
   "Gardenhead / Leave Me Alone",
   "She Did a Lot of Acid",
   "Ruby Bulbs / unknown (\"swimming in your speakers\")"
  ],
  "links": []
 },
 {
  "date": "1997-03-07",
  "year": 1997,
  "venue": "Jittery Joe's",
  "city": "Athens, GA",
  "format": "audio & video",
  "source": "audience",
  "quality": "good",
  "length": "48m",
  "lineage": null,
  "no_recording": false,
  "notes": "Jeff Mangum solo acoustic performance in 'The Starlit Crypt' at a coffeehouse in Athens, GA. Officially released as Jeff Mangum - Live At Jittery Joe's. In addition to audio playable on a normal CD player, it's an enhanced CD that includes QuickTime video of the entire show, shot by film maker Lance Bangs.",
  "setlist": [
   "introduction",
   "A Baby For Pree",
   "Two-Headed Boy",
   "I Will Bury You In Time",
   "Gardenhead / Leave Me Alone",
   "Two-Headed Boy Pt. 2",
   "I Love How You Love Me",
   "Engine",
   "Naomi",
   "King of Carrot Flowers Pt. 2",
   "King of Carrot Flowers Pt. 3",
   "Oh Comely"
  ],
  "links": []
 },
 {
  "date": "1997-03-27",
  "year": 1997,
  "venue": "40 Watt",
  "city": "Athens, GA",
  "format": "audio",
  "source": "?",
  "quality": "?",
  "length": "?",
  "lineage": null,
  "no_recording": false,
  "notes": "In March '06, a guy going by \"thehordak\" posted to the NMH message board about taping this show. Unfortunately, he wasn't in a hurry to share it, but seemed willing to eventually let people hear it. So I guess us fans will just have to wait patiently.\n\"I have a recording from the March 27th, 1997 40 Watt Show. Elf Power, Of Montreal, and Neutral Milk Hotel. I had a 4 track set up in the back of the club near the sound booth where they had the couches.\"",
  "setlist": [],
  "links": []
 },
 {
  "date": "1997-04-23",
  "year": 1997,
  "venue": "Tokyo Rose",
  "city": "Charlottesville, VA",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "53m",
  "lineage": null,
  "no_recording": false,
  "notes": "First show of the '97 US tour. It's an acoustic set by Jeff, with occasional accompaniment of accordion or horns. Jeremy Barnes was away in Chicago, so there's no drums. The performance includes a few rarely played songs, including \"April 8th\" and \"Bucket\" (by request). Jeff whistles a solo at the end of \"King of Carrot Flowers Pt 3\", which is something kinda cool I haven't noticed in other shows. Technical problems with the PA cutting out affect some of the first few songs. Some tape hiss on the recording.",
  "setlist": [
   "Gardenhead/Leave Me Alone",
   "Two-Headed Boy",
   "Song Against Sex",
   "I Will Bury You In Time",
   "The King of Carrot Flowers Pt. 3",
   "Naomi",
   "April 8th",
   "Bucket",
   "Acid (Pt. 1)",
   "Acid (Pt. 2)",
   "Ruby Bulbs",
   "unknown (\"swimming in your speakers\")",
   "A Baby For Pree",
   "Oh Comely"
  ],
  "links": []
 },
 {
  "date": "1997-04-24",
  "year": 1997,
  "venue": "Silk City Lounge",
  "city": "Philadelphia, PA",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "52m",
  "lineage": null,
  "no_recording": false,
  "notes": "This seems to be the earliest known recording of the song \"In The Aeroplane Over the Sea\". And like the other versions from mid '97, it seems to still be a work-in-progress, with different lyrics in the non-verse sections. Additionally, this show features two NMH songs that were rarely played live, \"Someone Is Waiting\" (by request) and \"You've Passed\".",
  "setlist": [
   "Oh Comely",
   "Gardenhead/Leave Me Alone",
   "A Baby For Pree",
   "Naomi",
   "Tuesday Moon",
   "Song Against Sex",
   "Message Sent (Through My Tears / Goldaline / \"now there is nothing\")",
   "In The Aeroplane Over The Sea",
   "Everything Is",
   "Ferris Wheel on Fire (aborted)",
   "The King of Carrot Flowers Pt. 3",
   "Someone Is Waiting",
   "You've Passed",
   "Two-Headed Boy"
  ],
  "links": []
 },
 {
  "date": "1997-04-25",
  "year": 1997,
  "venue": "Knitting Factory",
  "city": "New York, NY",
  "format": "audio",
  "source": "audience",
  "quality": "ok",
  "length": "64m",
  "lineage": null,
  "no_recording": false,
  "notes": "Jeff opens with some solo songs, including \"Sailing Through\" and \"I Will Bury You in Time\", both not played live all that often. On the recording, \"Goldaline\" (the middle section of \"Message Sent\") is cut, likely due to a tape flip on the master.",
  "setlist": [
   "Sailing Through",
   "I Will Bury You in Time",
   "Two-Headed Boy",
   "Oh Comely",
   "Naomi",
   "Gardenhead / Leave Me Alone",
   "Baby for Pree",
   "The Fool",
   "Message Sent [cut] (Through My Tears)",
   "Message Sent [cont.] (\"now there is nothing\")",
   "Ferris Wheel on Fire",
   "King of Carrot Flowers 2 & 3",
   "Everything Is",
   "Ruby Bulbs",
   "All the Colors of the Rainbow",
   "Snow Song pt 1",
   "Song Against Sex"
  ],
  "links": []
 },
 {
  "date": "1997-04-26",
  "year": 1997,
  "venue": "Terrastock",
  "city": "Providence, RI",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "36m",
  "lineage": null,
  "no_recording": false,
  "notes": "I think \"Naomi\" is supposed to be the last song on this show, but isn't.. at least not on the recording I have. There is also a professional soundboard recording of this performance, which has remained uncirculated, with the exception of \"Oh Comely\" which was released on a Blue Rose sampler cd.\nKevin O'Leary, co-owner of Flydaddy Records, said the label recorded the entire [Terrastock '97] festival, and is now trying to figure out how best to release the results to the world. [...] Judging by what he's heard so far, O'Leary said, sound quality is great, and he had high praise for engineers Tom Buckland and Toby Fitch.",
  "setlist": [
   "Oh Comely",
   "Gardenhead / Leave Me Alone",
   "A Baby for Pree",
   "The Fool",
   "Message Sent (Through My Tears / Goldaline)",
   "Message Sent [cont.] (\"now there is nothing\")",
   "Song Against Sex",
   "The King of Carrot Flowers Pts. 2 & 3",
   "Ruby Bulbs",
   "Snow Song Pt. 1"
  ],
  "links": []
 },
 {
  "date": "1997-04-27",
  "year": 1997,
  "venue": "Middle East",
  "city": "Cambridge, MA",
  "format": "audio",
  "source": "audience",
  "quality": "?",
  "length": "?",
  "lineage": null,
  "no_recording": false,
  "notes": "If you have this recording, please let me know.",
  "setlist": [],
  "links": []
 },
 {
  "date": "1997-04-28",
  "year": 1997,
  "venue": "Brownies",
  "city": "New York City, NY",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "51m",
  "lineage": null,
  "no_recording": false,
  "notes": "\"Acid\" is sometimes known as \"She Did a Lot of Acid\". Jeff says it doesn't really have a title, but they call it \"Acid\", and also says it probably won't ever be released.",
  "setlist": [
   "soundcheck jam / Acid",
   "Naomi",
   "In The Aeroplane Over The Sea",
   "Oh Comely",
   "King of Carrot Flowers Pts. 2 and 3",
   "Everything Is",
   "Gardenhead/Leave Me Alone",
   "Song Against Sex",
   "Message Sent / Ruby Bulbs (cut)",
   "Snow Song Pt 1"
  ],
  "links": []
 },
 {
  "date": "1997-05-01",
  "year": 1997,
  "venue": "Chicago",
  "city": "IL, Lounge Ax",
  "format": "audio",
  "source": "audience",
  "quality": "very good",
  "length": "55m",
  "lineage": null,
  "no_recording": false,
  "notes": "Very nice recording.",
  "setlist": [
   "Oh Comely",
   "Gardenhead/Leave Me Alone",
   "A Baby For Pree",
   "The Fool",
   "Tuesday Moon",
   "In the Aeroplane Over the Sea",
   "Message Sent (Through My Tears / Goldaline)",
   "Message Sent [cont.] (\"now there is nothing\")",
   "Song Against Sex",
   "Everything Is",
   "FerrisWheel on Fire",
   "Naomi",
   "Ruby Bulbs",
   "Snow Song pt 1",
   "The King of Carrot Flowers Pts. 2 & 3"
  ],
  "links": []
 },
 {
  "date": "1997-05-02",
  "year": 1997,
  "venue": "Rathskeller",
  "city": "Madison, WI",
  "format": "audio",
  "source": "soundboard",
  "quality": "ok",
  "length": "36m",
  "lineage": null,
  "no_recording": false,
  "notes": "A soundboard recording, this show sounds good at times and not so good other times.. there were problems with the soundboard. The Rathskeller is apparently a venue located in the University of Wisconsin.",
  "setlist": [
   "Naomi",
   "Gardenhead / Leave Me Alone",
   "Message Sent",
   "Tuesday Moon",
   "A Baby For Pree",
   "The Fool",
   "In The Aeroplane Over The Sea",
   "Song Against Sex",
   "Ruby Bulbs",
   "Snow Song Pt. 1"
  ],
  "links": []
 },
 {
  "date": "1997-05-03",
  "year": 1997,
  "venue": "7th Street Entry",
  "city": "Minneapolis, MN",
  "format": "audio",
  "source": "audience",
  "quality": "ok",
  "length": "38m",
  "lineage": null,
  "no_recording": false,
  "notes": "Jeff mentions they were supposed to play an in-store earlier that day, and apologizes for missing it, but says his \"dick broke\" so how can you argue with that?! No drummer for this show.",
  "setlist": [
   "King of Carrot Flowers pt 3",
   "She Did A Lot of Acid",
   "Naomi",
   "Gardenhead / Leave Me Alone",
   "Engine",
   "Song Against Sex",
   "In the Aeroplane Over the Sea",
   "A Baby For Pree",
   "The Fool",
   "Oh Comely"
  ],
  "links": []
 },
 {
  "date": "1997-05-05",
  "year": 1997,
  "venue": "Side Door",
  "city": "St. Louis, MO",
  "format": "audio",
  "source": "soundboard",
  "quality": "excellent",
  "length": "37m",
  "lineage": null,
  "no_recording": false,
  "notes": "Awesome soundboard recording, one of the best quality NMH bootlegs in circulation. There is also a low-quality audience recording of this show. At the beginning, Jeff mentions Jeremy couldn't make it, so it's a slightly more stripped-down show than usual. Also, Jeff says he and Scott have the flu, so he apologizes for a sloppy show. And he apologizes for his voice several times throughout the show.",
  "setlist": [
   "Acid",
   "Gardenhead / Leave Me Alone",
   "Naomi",
   "Engine",
   "King Of Carrot Flowers pt 3",
   "Song Against Sex",
   "The Fool",
   "Oh Comely",
   "In The Aeroplane Over The Sea"
  ],
  "links": []
 },
 {
  "date": "1997-05-06",
  "year": 1997,
  "venue": "Barrister's",
  "city": "Memphis, TN",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "30m",
  "lineage": null,
  "no_recording": false,
  "notes": "This show was just Jeff and Julian, as Scott was sick in the van, and Jeremy was still away. Olivia Tremor Control played too, and Jeff and Julian joined them for the last tune of their set.",
  "setlist": [
   "Oh Comely",
   "Naomi",
   "King Of Carrot Flowers pt 3",
   "I Will Bury You In Time",
   "Song Against Sex / Two-Headed Boy",
   "Gardenhead / Leave Me Alone"
  ],
  "links": []
 },
 {
  "date": "1997-05-16",
  "year": 1997,
  "venue": "40 Watt",
  "city": "Athens, GA",
  "format": "video",
  "source": "audience",
  "quality": "good",
  "length": "29m (there may be a 37m version?)",
  "lineage": null,
  "no_recording": false,
  "notes": "Kindercore Records 1st Anniversary Party, May 16th and 17th. Each night featured six bands, plus the Dixie Blood Moustache installation, and inspirational speaking by Michael Brian.\nThe line-up for Friday night: The Mendoza Line, Great Lakes, Of Montreal, Joe Christmas, Elf Power, Neutral Milk Hotel\nThe line-up for Saturday night: Nipples For Days, The Masters of the Hemisphere, Bunnygrunt, Gritty Kitty, Kincaid., The Olivia Tremor Control For Neutral Milk Hotel's set, they were joined on stage by members of Olivia Tremor Control and Elf Power.",
  "setlist": [
   "Two-Headed Boy",
   "Oh Comely",
   "Gardenhead / Leave Me Alone",
   "King of Carrot Flowers Pt. 3",
   "Message Sent (Through My Tears)",
   "Song Against Sex / end jam"
  ],
  "links": []
 },
 {
  "date": "1997-08-09",
  "year": 1997,
  "venue": "Seven South",
  "city": "Denver, CO",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "45m",
  "lineage": null,
  "no_recording": false,
  "notes": "Includes a rare live performance of \"Someone Is Waiting\". The recording is loud, but decent quality. This is a show the band did while in town to record Aeroplane. Interestingly, Jeff mentions that \"Message Sent\" might be on the record.. and I guess it sorta was, with the \"Goldaline\" section becoming part of \"Oh Comely\".",
  "setlist": [
   "intro/soundcheck",
   "Gardenhead / Leave Me Alone",
   "A Baby For Pree",
   "The Fool",
   "Tuesday Moon",
   "Message Sent (Through My Tears / Goldaline)",
   "Someone Is Waiting",
   "Ferris Wheel On Fire",
   "King Of Carrot Flowers Pts. 2 & 3",
   "Song Against Sex",
   "Naomi",
   "Ruby Bulbs",
   "Snow Song Pt. 1"
  ],
  "links": []
 },
 {
  "date": "1997-09-14",
  "year": 1997,
  "venue": "Broad River Outpost",
  "city": "Danielsville, GA",
  "format": "audio",
  "source": "soundboard",
  "quality": "excellent (mostly. see notes)",
  "length": "34m",
  "lineage": null,
  "no_recording": false,
  "notes": "The show was a benefit for the Broad River Action Group (BRAG) and marked the band's first performance since finishing recording Aeroplane. Highlights include the rarely played \"Someone Is Waiting\", plus what may be the final performances of \"Tuesday Moon\" and \"Message Sent\", which didn't seem to stick around in setlists for later tours. The recording is from the soundboard and was first circulated thanks to the mp3 blog Bicycle Kick My Worries Away in March 2006. The sound quality is great with the exception of slight tape hiss, plus some weird skipping for a few seconds in \"Naomi\" and \"Ruby Bulbs\".",
  "setlist": [
   "Naomi / Someone Is Waiting / Song Against Sex",
   "Tuesday Moon",
   "The King of Carrot Flowers Pt. 3 / A Baby For Pree",
   "Message Sent",
   "Gardenhead/Leave Me Alone / Ruby Bulbs / Snow Song Pt. 1"
  ],
  "links": []
 },
 {
  "date": "1997-10-14",
  "year": 1997,
  "venue": "40 Watt Club",
  "city": "Athens, GA",
  "format": "video",
  "source": "audience",
  "quality": "good",
  "length": "49m",
  "lineage": null,
  "no_recording": false,
  "notes": "Jeff solo acoustic.",
  "setlist": [
   "Two-Headed Boy (aborted)",
   "Gardenhead / Leave Me Alone",
   "King Of Carrot Flowers Pts.1, 2, 3",
   "A Baby For Pree",
   "In The Aeroplane Over The Sea",
   "I Will Bury You In Time",
   "Engine",
   "Holland, 1945",
   "Naomi",
   "Acid",
   "Ruby Bulbs / unknown (\"swimming in your speakers\")",
   "Oh Comely"
  ],
  "links": []
 },
 {
  "date": "1997-10-31",
  "year": 1997,
  "venue": "private home",
  "city": "Athens, GA",
  "format": "video",
  "source": "audience",
  "quality": "good",
  "length": "48:38",
  "lineage": null,
  "no_recording": false,
  "notes": "This was a Halloween party at a friend's house. The video made it into circulation in March '07. It's shot from right next to Jeff and is pretty nice quality. Before the show, there are several somewhat entertaining minutes as the band prepares to play, including Jeff talking to someone about Syd Barrett.\nThe show marks the first full-band live performance of \"Holland, 1945\".",
  "setlist": [
   "Two-Headed Boy Pt. Two",
   "The Fool",
   "The King of Carrot Flowers Pt. One",
   "Everything Is",
   "The King of Carrot Flowers Pts. Two and Three",
   "Naomi",
   "Gardenhead / Leave Me Alone",
   "Holland, 1945",
   "Ruby Bulbs",
   "All the Colors of the Rainbow",
   "Snow Song Pt. One"
  ],
  "links": []
 },
 {
  "date": "1997-11-21",
  "year": 1997,
  "venue": "40 Watt Club",
  "city": "Athens, GA",
  "format": "video",
  "source": "audience",
  "quality": "good",
  "length": "20m",
  "lineage": null,
  "no_recording": false,
  "notes": "Apparently an incomplete recording. Often mislabeled as \"1/1/98\", but 11/21/97 seems to be the correct date.",
  "setlist": [
   "In the Aeroplane Over the Sea",
   "Gardenhead / Leave Me Alone",
   "The King of Carrot Flowers Pts. Two & Three",
   "The King of Carrot Flowers Pt. One",
   "Song Against Sex"
  ],
  "links": []
 },
 {
  "date": "1997-11-22",
  "year": 1997,
  "venue": "Red Light Cafe",
  "city": "Atlanta, GA",
  "format": "audio",
  "source": "audience",
  "quality": "ok",
  "length": "34m",
  "lineage": null,
  "no_recording": false,
  "notes": "Earliest known live recording of \"Ghost\". Pretty funny version of \"All The Colors of the Rainbow\".\n\"Gardenhead / Leave Me Alone\" is a bit chaotic, and kinda breaks down a couple times.",
  "setlist": [
   "Gardenhead / Leave Me Alone",
   "A Baby for Pree / Where You'll Find Me Now",
   "The King of Carrot Flowers Pts. Two & Three",
   "Everything Is",
   "Song Against Sex",
   "Ruby Bulbs",
   "All the Colors of the Rainbow",
   "Snow Song Pt. One",
   "Naomi",
   "Ghost"
  ],
  "links": []
 },
 {
  "date": "1997-12-05",
  "year": 1997,
  "venue": "40 Watt Club",
  "city": "Athens, GA",
  "format": null,
  "source": null,
  "quality": null,
  "length": null,
  "lineage": null,
  "no_recording": true,
  "notes": "Opening for Vic Chesnut. Liz Durrett canceled so NMH stepped in. Their set included an early unreleased NMH song called \"My Skull\".",
  "setlist": [
   "Oh Comely",
   "The Fool",
   "Naomi",
   "Gardenhead",
   "My Skull",
   "Ferris Wheel on Fire",
   "Everything Is",
   "In The Aeroplane Over the Sea",
   "Holland 1945",
   "Two Headed Boy"
  ],
  "links": []
 },
 {
  "date": "1998-01-01",
  "year": 1998,
  "venue": "---> see 11/21/97",
  "city": "",
  "format": null,
  "source": null,
  "quality": null,
  "length": null,
  "lineage": null,
  "no_recording": false,
  "notes": "",
  "setlist": [],
  "links": []
 },
 {
  "date": "1998-02-04",
  "year": 1998,
  "venue": "40 Watt Club",
  "city": "Athens, GA",
  "format": "video",
  "source": "audience",
  "quality": "very good",
  "length": "54m",
  "lineage": null,
  "no_recording": false,
  "notes": "Pretty cool video. This was the first show of 1998.. the dawning of the \"Aeroplane era\" as it were.. a little hometown show before heading out on tour.",
  "setlist": [
   "Holland, 1945",
   "A Baby for Pree",
   "Everything Is",
   "Gardenhead / Leave Me Alone",
   "Naomi",
   "Oh Comely",
   "The Fool",
   "The King of Carrot Flowers Pts. Two & Three",
   "Ghost",
   "Song for Ché",
   "Worms in the Wind",
   "Song Against Sex",
   "Snow Song Pt. One"
  ],
  "links": []
 },
 {
  "date": "1998-02-07",
  "year": 1998,
  "venue": "Cow Haus",
  "city": "Tallahassee, FL",
  "format": "audio",
  "source": "audience",
  "quality": "very good",
  "length": "63m",
  "lineage": null,
  "no_recording": false,
  "notes": "The 1998 Florida Popfest. Fifteen bands played: Neutral Milk Hotel, Kincaid, The Mountain Goats, Racecar, True Love Always, Congratulations, Of Montreal, Masters of the Hemisphere, Crush 22, Silver Apples, The Gerbils, Gritty Kitty, Four Head, Elf Power, and The Music Tapes. Here's a little review by Chris M.: it seemed like that was the show where everyone, the fans, Jeff, the rest of the band, realised something more was going on here than just another \"indie pick of the month\". The festival was two or three nights if I remember and NMH were to close the last night of the festival. Because of various delays, NMH didn't get to come on until about 2 am. You would think most of the kids would have been exhausted by this point and shuffling home. But they didn't. The place was packed and it seemed as if the whole crowd was one person, all jumping and screaming every last word Jeff was singing back at him. I have a great memory of Jeff looking back at Julian with this, \"What the hell is all this about?\" look.\nMany versions of this show are incomplete, usually ending at about 45 minutes with a cut in the middle of \"Snow Song\".",
  "setlist": [
   "Two-Headed Boy",
   "The Fool",
   "A Baby For Pree",
   "Holland, 1945",
   "Naomi",
   "Gardenhead / Leave Me Alone",
   "Song For Ché",
   "Ghost",
   "Everything Is",
   "The King Of Carrot Flowers, Pts 2 & 3",
   "Song Against Sex",
   "Snow Song Pt 1",
   "In The Aeroplane Over The Sea",
   "Ferris Wheel On Fire"
  ],
  "links": []
 },
 {
  "date": "1998-02-15",
  "year": 1998,
  "venue": "Young Avenue Deli",
  "city": "Memphis, TN",
  "format": null,
  "source": null,
  "quality": null,
  "length": null,
  "lineage": null,
  "no_recording": true,
  "notes": "",
  "setlist": [
   "Oh Comely",
   "The Fool",
   "A Baby for Pree",
   "Everything Is",
   "Naomi",
   "Holland, 1945",
   "In the Aeroplane Over the Sea",
   "Gardenhead / Leave Me Alone",
   "Ghost",
   "The King of Carrot Flowers Pts. 2 and 3",
   "Song Against Sex",
   "Snow Song Pt. One"
  ],
  "links": []
 },
 {
  "date": "1998-02-26",
  "year": 1998,
  "venue": "Sudsy Malone's",
  "city": "Cincinnati, OH",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "52m",
  "lineage": null,
  "no_recording": false,
  "notes": "Some versions of this recording are only 46 minutes long, and are missing a couple minutes off both the beginning and end. The reason several NMH shows are incomplete at 45 or 46 minutes dates back to the days when cassette tape trading was the main route for fans (before CDRs and digital formats made tapes obsolete). One side of a 90 minute tape is about 46 minutes. Sometimes traders were lazy and didn't bother to include the rest of the show. Sometimes the master tapes were cut due to lazy tapers.",
  "setlist": [
   "Two-Headed Boy",
   "The Fool",
   "King Of Carrot Flowers Pt.2 & 3",
   "Everything Is",
   "Gardenhead / Leave Me Alone",
   "Holland, 1945",
   "Ferris Wheel On Fire",
   "Ghost",
   "Naomi",
   "Song Against Sex",
   "Ruby Bulbs",
   "Snow Song Pt. One"
  ],
  "links": []
 },
 {
  "date": "1998-02-27",
  "year": 1998,
  "venue": "Graffiti",
  "city": "Pittsburgh, PA",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "46m",
  "lineage": null,
  "no_recording": false,
  "notes": "",
  "setlist": [
   "Two-Headed Boy Pt. 2",
   "The Fool",
   "A Baby for Pree",
   "Gardenhead",
   "Naomi",
   "In the Aeroplane Over the Sea",
   "Ghost",
   "King of Carrot Flowers Pts. 2 & 3",
   "Song Against Sex",
   "Ruby Bulbs",
   "Snow Song Pt. One"
  ],
  "links": []
 },
 {
  "date": "1998-03-04",
  "year": 1998,
  "venue": "Cat’s Cradle",
  "city": "Chapel Hill, NC",
  "format": "audio",
  "source": "audience",
  "quality": "very good",
  "length": "53m",
  "lineage": null,
  "no_recording": false,
  "notes": "This bootleg is quite common online. Solid show.",
  "setlist": [
   "Oh Comely",
   "The Fool",
   "A Baby For Pree",
   "Everything Is",
   "Naomi",
   "Ghost",
   "Song For Ché",
   "Engine",
   "The King of Carrot Flowers Pts. Two and Three",
   "Holland, 1945",
   "Song Against Sex",
   "Ruby Bulbs",
   "Snow Song Pt. One"
  ],
  "links": []
 },
 {
  "date": "1998-03-07",
  "year": 1998,
  "venue": "Knitting Factory",
  "city": "New York, NY",
  "format": "video",
  "source": "audience",
  "quality": "very good",
  "length": "?",
  "lineage": null,
  "no_recording": false,
  "notes": "Rarely-played track alert: \"April 8th\" Apparently, someone up front was video taping this show, though as far as I know, the recording has not been circulated at all.\nUPDATE! In November 2009, the taper began posting songs from this show on YouTube. The set wasn't filmed in its entirety, unfortunately.",
  "setlist": [
   "Two-Headed Boy",
   "April 8th",
   "Oh Comely",
   "The Fool",
   "The King of Carrot Flowers Pts. Two & Three",
   "Naomi",
   "Ghost",
   "Gardenhead / Leave Me Alone",
   "Holland, 1945",
   "In the Aeroplane Over the Sea",
   "A Baby for Pree",
   "Everything Is",
   "Song Against Sex",
   "Ferris Wheel on Fire",
   "Snow Song Pt. One"
  ],
  "links": []
 },
 {
  "date": "1998-03-08",
  "year": 1998,
  "venue": "Middle East",
  "city": "Cambridge, MA",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "62m",
  "lineage": null,
  "no_recording": false,
  "notes": "",
  "setlist": [
   "Oh Comely",
   "The Fool",
   "King of Carrot Flowers pts 2 and 3",
   "Naomi",
   "Ghost",
   "Two-Headed Boy",
   "Gardenhead / Leave Me Alone",
   "Holland, 1945",
   "In The Aeroplane Over The Sea",
   "A Baby For Pree",
   "Everything Is",
   "Song Against Sex",
   "Ruby Bulbs / Snow Song Pt. One"
  ],
  "links": []
 },
 {
  "date": "1998-03-16",
  "year": 1998,
  "venue": "The Point",
  "city": "Atlanta, GA",
  "format": null,
  "source": null,
  "quality": null,
  "length": null,
  "lineage": null,
  "no_recording": true,
  "notes": "",
  "setlist": [
   "Oh Comely",
   "The Fool",
   "The King of Carrot Flowers Pts. Two & Three",
   "Naomi",
   "Ghost",
   "Two-Headed Boy",
   "Gardenhead / Leave Me Alone",
   "Holland, 1945",
   "In the Aeroplane Over the Sea",
   "Song Against Sex",
   "Ruby Bulbs",
   "Snow Song Pt. One"
  ],
  "links": []
 },
 {
  "date": "1998-03-28",
  "year": 1998,
  "venue": "40 Watt Club",
  "city": "Athens, GA",
  "format": null,
  "source": null,
  "quality": null,
  "length": null,
  "lineage": null,
  "no_recording": true,
  "notes": "",
  "setlist": [
   "Two-Headed Boy Pt. Two",
   "The King of Carrot Flowers Pts. Two & Three",
   "Holland, 1945",
   "A Baby for Pree",
   "Ferris Wheel on Fire",
   "Song Against Sex",
   "Ruby Bulbs",
   "Snow Song Pt. One",
   "Ghost",
   "untitled"
  ],
  "links": []
 },
 {
  "date": "1998-04-03",
  "year": 1998,
  "venue": "Mermaid Lounge",
  "city": "New Orleans, LA",
  "format": "audio",
  "source": "soundboard",
  "quality": "good or excellent (see notes)",
  "length": "53m",
  "lineage": null,
  "no_recording": false,
  "notes": "This was kind of like a homecoming show for Jeff, who grew up in nearby Ruston, Louisiana, and he mentions that his mom and sister are in attendance. The recording is a soundboard/audience hybrid. They had a mixing board in the back and mixed the soundboard live to DAT, incorporating a room mic into the mix. The more circulated version of this recording badly overloads in the loud parts, plus the end of \"Ghost\" is cut off and \"untitled\" is missing. But there is also a version that sounds much better, and includes \"Ghost\"/\"untitled\" completely, though that better version is missing the final 2 songs.",
  "setlist": [
   "Two-Headed Boy",
   "The Fool",
   "Worms in the Wind",
   "King of Carrot Flowers pt 2 and 3",
   "Holland, 1945",
   "Naomi",
   "Gardenhead / Leave Me Alone",
   "In The Aeroplane Over the Sea",
   "Song Against Sex",
   "Ruby Bulbs",
   "Snow Song pt 1",
   "Ghost",
   "untitled",
   "A Baby For Pree",
   "Everything Is"
  ],
  "links": []
 },
 {
  "date": "1998-04-04",
  "year": 1998,
  "venue": "Electric Lounge",
  "city": "Austin, TX",
  "format": "video",
  "source": "audience",
  "quality": "good",
  "length": "44m",
  "lineage": null,
  "no_recording": false,
  "notes": "Decent video, but the person filming the show felt the need to get \"artsy\" and use a bunch of effects on the video.. so several songs are shot with the color inverted (so instead of some white guys playing in the dark, it looks like black guys playing in heaven) and other songs are shot with a brown hue. You can hear him making comments about it, so it's definitely on the master, not a post-production effect, unfortunately. But the sound is good, and some songs are filmed okay.\nI attempted to fix the show up a little, and this version has circulated on DVD among fans.",
  "setlist": [
   "Oh Comely",
   "The Fool",
   "Naomi",
   "Holland, 1945",
   "Worms In The Wind / King Of Carrot Flowers 2 & 3",
   "Gardenhead / Leave Me Alone",
   "In The Aeroplane Over The Sea",
   "Ruby Bulbs",
   "Snow Song Pt. 1",
   "Ghost / untitled"
  ],
  "links": []
 },
 {
  "date": "1998-04-10",
  "year": 1998,
  "venue": "Spaceland",
  "city": "Silver Lake, CA",
  "format": null,
  "source": null,
  "quality": null,
  "length": null,
  "lineage": null,
  "no_recording": false,
  "notes": "This show is known to have been taped, but unfortunately has not really circuated at all. Maybe someday. If you have a copy, please let me know.",
  "setlist": [],
  "links": []
 },
 {
  "date": "1998-04-11",
  "year": 1998,
  "venue": "Bottom of the Hill",
  "city": "San Francisco, CA",
  "format": "video",
  "source": "audience",
  "quality": "good",
  "length": "67m",
  "lineage": null,
  "no_recording": false,
  "notes": "A review of this show was posted on the now-defunct music news website SonicNet, and can currently be found at VH1's site.\nThe review states that the show was 90 minutes. If that's accurate, that would mean the recording is incomplete.",
  "setlist": [
   "Oh Comely",
   "The Fool",
   "Worms In The Wind / King Of Carrot Flowers 2 & 3",
   "Holland, 1945",
   "Naomi",
   "Gardenhead / Leave Me Alone",
   "In The Aeroplane Over The Sea",
   "Song Against Sex",
   "Ruby Bulbs",
   "Snow Song Pt. 1",
   "Two-Headed Boy",
   "Ghost / untitled",
   "Engine"
  ],
  "links": []
 },
 {
  "date": "1998-04-12",
  "year": 1998,
  "venue": "Bottom of the Hill",
  "city": "San Francisco, CA",
  "format": "video & audio",
  "source": "audience",
  "quality": "good",
  "length": "90m video; 74m audio",
  "lineage": null,
  "no_recording": false,
  "notes": "In addition to video, there is also an audio recording of this show, which is readily available online via mp3s. Great show with some rarely played songs. Also, clocking in at about 81 minutes, it seems to be the longest NMH show in circulation, though some audio versions are a few minutes shorter thanks to editing out some downtime between songs. Some versions of the video include about 10 minutes of the soundcheck, with the band playing \"Song for Ché\" and part of the end of \"Ghost\" before the show.",
  "setlist": [
   "Sailing Through",
   "Two-Headed Boy pt 2",
   "Holland 1945",
   "Gardenhead / Leave Me Alone",
   "A Baby for Pree",
   "Ferris Wheel on Fire",
   "Worms in the Wind / King of Carrot Flowers pts. 2 & 3",
   "Song Against Sex",
   "Ruby Bulbs",
   "unknown (\"swimming in your speakers\")",
   "Snow Song pt. 1",
   "Naomi",
   "I Will Bury You in Time",
   "Ghost / untitled",
   "Oh Comely",
   "King of Carrot Flowers pt 1",
   "Two-Headed Boy"
  ],
  "links": []
 },
 {
  "date": "1998-04-14",
  "year": 1998,
  "venue": "Crocodile Cafe",
  "city": "Seattle, WA",
  "format": "audio",
  "source": "audience [Sony D3]",
  "quality": "good",
  "length": "45m",
  "lineage": null,
  "no_recording": false,
  "notes": "",
  "setlist": [
   "Two-Headed Boy",
   "The Fool",
   "Holland, 1945",
   "Worms in the Wind",
   "King Of Carrot Flowers, Pts. Two & Three",
   "Naomi",
   "In The Aeroplane Over The Sea",
   "[technical difficulties]",
   "A Baby For Pree",
   "Song Against Sex",
   "Ruby Bulbs",
   "Snow Song, Pt. One",
   "Ghost",
   "untitled"
  ],
  "links": []
 },
 {
  "date": "1998-04-15",
  "year": 1998,
  "venue": "Satyricon",
  "city": "Portland, OR",
  "format": null,
  "source": null,
  "quality": null,
  "length": null,
  "lineage": null,
  "no_recording": true,
  "notes": "",
  "setlist": [
   "Two-Headed Boy",
   "The Fool",
   "King of Carrot Flowers Pts 2 and 3",
   "Holland, 1945",
   "Naomi",
   "Gardenhead / Leave Me Alone",
   "In The Aeroplane Over The Sea",
   "Song Against Sex",
   "Ruby Bulbs",
   "Snow Song Pt One",
   "Ghost",
   "untitled"
  ],
  "links": []
 },
 {
  "date": "1998-04-18",
  "year": 1998,
  "venue": "Terrastock II",
  "city": "San Francisco, CA",
  "format": "audio",
  "source": "soundboard (KFJC FM)",
  "quality": "excellent",
  "length": "47:28",
  "lineage": null,
  "no_recording": false,
  "notes": "Terrastock II was a festival that took place the weekend of April 17-19 of 1998 at the Custer Avenue Stages in San Francisco. The soundboard recording is from an FM radio broadcast, and depending on the source/generation, sounds anywhere from very good to incredible (there may also be audience recordings of this show). Some copies are missing the first 2 songs, and many are missing the end of the last track.",
  "setlist": [
   "introduction",
   "Two-Headed Boy",
   "The Fool",
   "Worms in the Wind",
   "The King of Carrot Flowers Pts. Two and Three",
   "Holland, 1945",
   "A Baby for Pree",
   "Ferris Wheel on Fire",
   "In the Aeroplane Over the Sea",
   "Gardenhead / Leave Me Alone",
   "Song Against Sex",
   "Ruby Bulbs",
   "Snow Song Pt. One",
   "Ghost",
   "untitled"
  ],
  "links": []
 },
 {
  "date": "1998-04-24",
  "year": 1998,
  "venue": "400 Bar",
  "city": "Minneapolis, MN",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "64m",
  "lineage": null,
  "no_recording": false,
  "notes": "Technical difficulties and \"brain melting\" by band members plague some of the first few tracks. \"Naomi\", in particular, is a train wreck.\nJeff throws in a quick rendition of \"All The Colors of the Rainbow\" in the middle of \"Ruby Bulbs\" before eventually transitioning into an epic version of \"Snow Song Part 1\".",
  "setlist": [
   "Two-Headed Boy",
   "The Fool",
   "The King of Carrot Flowers Pts. 2 and 3",
   "Holland, 1945",
   "Naomi",
   "Gardenhead/Leave Me Alone",
   "In The Aeroplane Over The Sea",
   "A Baby For Pree",
   "Song Against Sex / Ruby Bulbs / All The Colors of the Rainbow / Snow Song Pt. 1",
   "Ghost / untitled",
   "Two-Headed Boy Pt. 2",
   "Ferris Wheel on Fire"
  ],
  "links": []
 },
 {
  "date": "1998-04-25",
  "year": 1998,
  "venue": "Lounge Ax",
  "city": "Chicago, IL",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "63m",
  "lineage": null,
  "no_recording": false,
  "notes": "Decent recording, though the crowd is a bit annoying at times.",
  "setlist": [
   "intro (Worms In The Wind spoken)",
   "King of Carrot Flowers 1",
   "King of Carrot Flowers 2-3",
   "Two-Headed Boy pt. 2",
   "Holland, 1945",
   "Naomi",
   "Gardenhead / Leave Me Alone",
   "In the Aeroplane Over the Sea",
   "Song Against Sex",
   "Ruby Bulbs",
   "Snow Song pt 1",
   "Two-Headed Boy",
   "The Fool",
   "Ghost",
   "untitled",
   "A Baby for Pree / Ferris Wheel on Fire"
  ],
  "links": []
 },
 {
  "date": "1998-05-22",
  "year": 1998,
  "venue": "12 Bar Club",
  "city": "London, UK",
  "format": "audio",
  "source": "audience",
  "quality": "ok",
  "length": "47m",
  "lineage": null,
  "no_recording": false,
  "notes": "The band was nervous, as it was their first show outside the US. The first song is sometimes mislabeled as \"Ghost\" on this recording.",
  "setlist": [
   "Oh Comely",
   "The Fool",
   "King of Carrot Flowers Pts 2 & 3",
   "Holland, 1945",
   "Two-Headed Boy",
   "Naomi",
   "In The Aeroplane Over The Sea",
   "A Baby For Pree",
   "Song Against Sex",
   "Ruby Bulbs",
   "Snow Song Pt 1"
  ],
  "links": []
 },
 {
  "date": "1998-05-23",
  "year": 1998,
  "venue": "12 Bar Club",
  "city": "London, UK",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "48m",
  "lineage": null,
  "no_recording": false,
  "notes": "The master recording source is a Sony Minidisc.",
  "setlist": [
   "Two-Headed Boy Pt. 2",
   "The Fool",
   "Naomi",
   "Holland, 1945",
   "Gardenhead/Leave Me Alone",
   "In The Aeroplane Over The Sea",
   "King Of Carrot Flowers Pts.2 & 3",
   "Oh Comely",
   "Song Against Sex",
   "Ruby Bulbs",
   "Snow Song Pt.1"
  ],
  "links": []
 },
 {
  "date": "1998-05-??",
  "year": 1998,
  "venue": "XFM",
  "city": "London, UK",
  "format": "audio",
  "source": "radio broadcast",
  "quality": "excellent",
  "length": "29m",
  "lineage": null,
  "no_recording": false,
  "notes": "While NMH was in London for a couple shows, Jeff stopped in at XFM studios for a radio appearance. It included an 11 minute interview and 4 solo acoustic songs. It wasn't broadcast live, but rather played in parts over a week a month later (June 21 thru 25):\ninterview (broadcast on 21 June 1998)\nGardenhead (21 June 1998)\nEngine (22 June 1998, repeated 25 June 1998)\nUp & Over Again [sic] (23 June 1998)\nOh Comely (24 June 1998) This recording is often misdated 18 August 1998. It's possible this session was rebroadcast in August, but it was definitely originally recorded in May.",
  "setlist": [
   "interview",
   "Gardenhead/Leave Me Alone",
   "Engine",
   "King of Carrot Flowers Pt. 3",
   "Oh Comely"
  ],
  "links": []
 },
 {
  "date": "1998-06-29",
  "year": 1998,
  "venue": "Sapphire Supper Club",
  "city": "Orlando, FL",
  "format": "audio",
  "source": "audience",
  "quality": "ok",
  "length": "50m",
  "lineage": null,
  "no_recording": false,
  "notes": "Some versions of this recording are missing \"Ruby Bulbs\". I guess Jeremy Barnes couldn't be at the show for some reason, so the band performs without drums.",
  "setlist": [
   "Oh Comely",
   "Naomi",
   "Two-Headed Boy",
   "Engine",
   "Holland, 1945",
   "In the Aeroplane Over the Sea",
   "The King of Carrot Flowers Pt. One",
   "Ferris Wheel on Fire",
   "Ruby Bulbs",
   "Song Against Sex",
   "Snow Song Pt. One"
  ],
  "links": []
 },
 {
  "date": "1998-07-11",
  "year": 1998,
  "venue": "40 Watt Club",
  "city": "Athens, GA",
  "format": "video",
  "source": "audience",
  "quality": "poor",
  "length": "51m",
  "lineage": null,
  "no_recording": false,
  "notes": "Decent picture for the video, but bad sound. Also, a couple songs are partially cut. The Athens Summer Music Extravaganza (a.k.a Kindercore Pop Festival) with Wolfie, Elf Power, Bunnygrunt, Dressy Bessy, Gritty Kitty, The Push Kings, Sukpatch, Aden, The Gerbils, Tullycraft, Kincaid, The Autumn Teen Sound, The Ladybug Transistor, The Olivia Tremor Control, Darling Little Jackhammer, Six Cents and Natalie, The Masters of the Hemisphere, The Minders, Junior Varsity, Of Montreal, and Neutral Milk Hotel.",
  "setlist": [
   "A Baby for Pree",
   "Holland, 1945",
   "Naomi",
   "The King of Carrot Flowers Pts. Two and Three",
   "In the Aeroplane Over the Sea",
   "Two-Headed Boy Pt. Two",
   "The Fool",
   "Everything Is",
   "Song Against Sex",
   "Ruby Bulbs",
   "Snow Song Pt. One",
   "Ghost",
   "untitled"
  ],
  "links": []
 },
 {
  "date": "1998-07-22",
  "year": 1998,
  "venue": "Black Cat",
  "city": "Washington, DC",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "61m",
  "lineage": null,
  "no_recording": false,
  "notes": "Technical difficulties abound, at one point even causing Jeff to say, \"This is the most fucked show I've ever played in my life!\" But despite that, both the band and the crowd are in good spirits, and it's a pretty solid show.",
  "setlist": [
   "A Baby for Pree",
   "Holland, 1945",
   "Naomi",
   "In the Aeroplane Over the Sea",
   "Two-Headed Boy Pt. Two",
   "The King of Carrot Flowers Pt. Two (aborted)",
   "The King of Carrot Flowers Pts. Two and Three",
   "Gardenhead / Leave Me Alone",
   "Ghost",
   "Song Against Sex",
   "Ruby Bulbs",
   "Snow Song Pt. One",
   "Oh Comely",
   "The Fool"
  ],
  "links": []
 },
 {
  "date": "1998-07-24",
  "year": 1998,
  "venue": "Middle East",
  "city": "Cambridge, MA",
  "format": "audio",
  "source": "audience",
  "quality": "poor",
  "length": "53m",
  "lineage": null,
  "no_recording": false,
  "notes": "Some versions of this recording seem to be missing the last 3 songs. A review of this show is online at lunakafe.com.",
  "setlist": [
   "A Baby for Pree",
   "Holland, 1945",
   "Naomi",
   "In the Aeroplane Over the Sea",
   "The King of Carrot Flowers Pt. One",
   "The King of Carrot Flowers Pt. Two and Three",
   "Ghost",
   "Song Against Sex",
   "Ruby Bulbs",
   "Gardenhead / Leave Me Alone",
   "Two-Headed Boy Pt. Two",
   "The Fool / Snow Song Pt. One"
  ],
  "links": []
 },
 {
  "date": "1998-07-25",
  "year": 1998,
  "venue": "Bowery Ballroom",
  "city": "New York, NY",
  "format": "audio",
  "source": "audience",
  "quality": "?",
  "length": "50m",
  "lineage": null,
  "no_recording": false,
  "notes": "This show doesn't seem to be in circulation amongst fans, but it was apparently recorded by someone named Patti Vill. Hey Patti, are you out there? Let's trade!",
  "setlist": [
   "A Baby for Pree",
   "Holland, 1945",
   "Naomi",
   "In the Aeroplane Over the Sea",
   "The King of Carrot Flowers Pt. One",
   "The King of Carrot Flowers Pts. Two and Three",
   "Two-Headed Boy",
   "The Fool",
   "Engine",
   "Song Against Sex",
   "Ruby Bulbs",
   "Gardenhead / Leave Me Alone",
   "Ghost",
   "untitled"
  ],
  "links": []
 },
 {
  "date": "1998-07-26",
  "year": 1998,
  "venue": "Maxwell's",
  "city": "Hoboken, NJ",
  "format": "audio",
  "source": "soundbaord",
  "quality": "excellent",
  "length": "68m",
  "lineage": null,
  "no_recording": false,
  "notes": "This show was unearthed in mid 2020, making it a recent addition to the OG circulating live recordings. Worth the wait, as the sound quality and performance are both top-notch. Jeff sings a little bonus song during the beginning of “King of Carrot Flowers Pt 2”, which is apparently a snippet of a Cranberry Lifecycle song from 1991 called “Margaret Ann McKay”.",
  "setlist": [
   "Oh Comely",
   "On Avery Island / April 1st",
   "Naomi",
   "Ghost",
   "untitled",
   "Holland, 1945",
   "In the Aeroplane Over the Sea",
   "Song Against Sex",
   "Snow Song Pt. One",
   "A Baby for Pree",
   "The King of Carrot Flowers Pts. Two and Three",
   "Everything Is",
   "Gardenhead / Leave Me Alone",
   "Ruby Bulbs",
   "Two-Headed Boy",
   "The Fool"
  ],
  "links": []
 },
 {
  "date": "1998-07-30",
  "year": 1998,
  "venue": "The Bug Jar",
  "city": "Rochester, NY",
  "format": "audio",
  "source": "soundboard / radio broadcast",
  "quality": "very good",
  "length": "51m",
  "lineage": null,
  "no_recording": false,
  "notes": "Radio broadcast. From \"Universal Buzz Radio Network\". There's a promo CD of the broadcast, but most circulating versions seems to be taped off the radio, as the sound is a bit muffled. (If anyone has a real copy of the Universal Buzz promo cd, please let me know.) It was also available streaming online for a while. There are commercial intros by the DJ, and the bad words have been edited (I think there's just one.. in \"Naomi\").\nThere is apparently also an audience recording of this same show.. lower quality, obviously.\nThe show features a rare live recording of \"Avery Island / April 1st\".",
  "setlist": [
   "Oh Comely",
   "Avery Island / April 1st",
   "Naomi",
   "A Baby For Pree",
   "Holland, 1945",
   "King Of Carrot Flowers Pts 2 & 3",
   "In The Aeroplane Over The Sea",
   "Song Against Sex",
   "Ruby Bulbs",
   "Snow Song Pt. 1",
   "Ghost",
   "untitled"
  ],
  "links": []
 },
 {
  "date": "1998-08-18",
  "year": 1998,
  "venue": "XFM Session --> see 5/?/98",
  "city": "",
  "format": null,
  "source": null,
  "quality": null,
  "length": null,
  "lineage": null,
  "no_recording": false,
  "notes": "",
  "setlist": [],
  "links": []
 },
 {
  "date": "1998-08-18",
  "year": 1998,
  "venue": "The Garage",
  "city": "London, England",
  "format": "audio",
  "source": "audience",
  "quality": "very good",
  "length": "44m",
  "lineage": null,
  "no_recording": false,
  "notes": "Many fans point to this as one of the best NMH bootlegs out there. The recording sounds very nice, and the band is in top form.",
  "setlist": [
   "Oh Comely",
   "The Fool",
   "A Baby For Pree",
   "Holland, 1945",
   "King Of Carrot Flowers Pts. 2 and 3",
   "Everything Is",
   "King Of Carrot Flowers Pt. 1",
   "In The Aeroplane Over The Sea",
   "Song Against Sex",
   "Ruby Bulbs",
   "Ghost",
   "untitled"
  ],
  "links": []
 },
 {
  "date": "1998-09-14",
  "year": 1998,
  "venue": "Concorde",
  "city": "Brighton, England",
  "format": null,
  "source": null,
  "quality": null,
  "length": null,
  "lineage": null,
  "no_recording": true,
  "notes": "",
  "setlist": [
   "Two-Headed Boy",
   "The Fool",
   "The King of Carrot Flowers Pts. Two and Three",
   "Holland, 1945",
   "In the Aeroplane Over the Sea",
   "Song Against Sex",
   "Song for Che",
   "Ghost",
   "untitled"
  ],
  "links": []
 },
 {
  "date": "1998-09-18",
  "year": 1998,
  "venue": "Pusterviksbaren",
  "city": "Gothenburg, Sweden",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "39m",
  "lineage": null,
  "no_recording": false,
  "notes": "Technical difficulties put a damper on the show, but both the band and the crowd still seem in good spirits.",
  "setlist": [
   "Two-Headed Boy",
   "The Fool",
   "The King of Carrot Flowers Pts. Two and Three",
   "Holland, 1945",
   "Naomi",
   "Ferris Wheel on Fire",
   "Ghost",
   "untitled",
   "Song Against Sex",
   "Song for Ché"
  ],
  "links": []
 },
 {
  "date": "1998-10-10",
  "year": 1998,
  "venue": "University MDH",
  "city": "Manchester, England",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "41m",
  "lineage": null,
  "no_recording": false,
  "notes": "This is the latest* full-band NMH live recording in circulation. (*from the original run; They did some reunion touring since I wrote these blurbs, of course!)",
  "setlist": [
   "Oh Comely",
   "The Fool",
   "King Of Carrot Flowers Pts. 2 & 3",
   "Holland, 1945",
   "Naomi",
   "In The Aeroplane Over The Sea",
   "Song Against Sex / Ruby Bulbs",
   "Ghost"
  ],
  "links": []
 },
 {
  "date": "1998-10-13",
  "year": 1998,
  "venue": "Peter Curran Show, GLR",
  "city": "London, England",
  "format": "audio",
  "source": "radio broadcast",
  "quality": "very good",
  "length": "9m",
  "lineage": null,
  "no_recording": false,
  "notes": "This recording had been erroneously referred to as \"Capitol Radio Session\" when it first started circulating online, but it has since been revealed to actually be from GLR. Those familiar with London radio know Capitol is far too mainstream pop to ever play NMH. Some versions skip in \"Naomi\". Also in the song, Jeff censors himself, saying \"she smells like eggs\" instead of \"shit\".",
  "setlist": [
   "interview",
   "Naomi",
   "interview (contest for listeners)"
  ],
  "links": []
 },
 {
  "date": "1998-12-05",
  "year": 1998,
  "venue": "Athens",
  "city": "GA",
  "format": "video",
  "source": "audience",
  "quality": "good",
  "length": "30m",
  "lineage": null,
  "no_recording": false,
  "notes": "Mostly Jeff solo/acoustic/seated. This show, which took place in an old school gymnasium, was a birthday party for Chris Bilheimer, who is like a behind-the-scenes member of R.E.M.\nIt features a rare performance of the unreleased song \"Little Birds\", this being the only known recording of it, live or otherwise.",
  "setlist": [
   "Little Birds",
   "Two-Headed Boy",
   "In The Aeroplane Over The Sea",
   "Holland 1945",
   "Everything Is",
   "Oh Comely (recording cuts off near the end)"
  ],
  "links": []
 },
 {
  "date": "1998-12-31",
  "year": 1998,
  "venue": "40 Watt",
  "city": "Athens, GA",
  "format": "video",
  "source": "audience",
  "quality": "good",
  "length": "13m",
  "lineage": null,
  "no_recording": false,
  "notes": "Short acoustic set by Jeff, with Julian Koster joining on saw and Scott Spillane on trumpet. Features a rare performance of \"Oh Sister\" by request. This show was basically the last the world would hear of Neutral Milk Hotel as anything close to an active band, and you can almost sense closure in the performance.\nVideo shot from close to the stage.\nAudio from this show is often packaged together with 12/5/98 (above) under the title \"Accordion Peas\".",
  "setlist": [
   "Engine",
   "Oh Sister",
   "In The Aeroplane Over The Sea"
  ],
  "links": []
 },
 {
  "date": "2001-02-04",
  "year": 2001,
  "venue": "King's Arms",
  "city": "Auckland, New Zealand",
  "format": "audio",
  "source": "soundboard",
  "quality": "excellent",
  "length": "52m",
  "lineage": null,
  "no_recording": false,
  "notes": "This is thought to be Jeff's first/last/only performance since 1998, and was the last time he played any NMH song live until 2008 (when he played \"Engine\" on the E6 Holiday Surprise tour, and in 2010 when he played a couple shows). This is basically a solo Jeff Mangum show under the name ‘Walking Wall of Beards, Inc.’ Jeff was joined by multi-instrumentalist Laura Carter on a few songs. Chris Knox joins for the last song (a John Lennon cover). Here is a link to a review and some pictures from the show.",
  "setlist": [
   "Two-Headed Boy",
   "I Love How You Love Me",
   "Song Against Sex",
   "King of Carrot Flowers pts. 1, 2, & 3",
   "Everything Is",
   "Gardenhead / Leave Me Alone",
   "Ghost",
   "Oh Comely",
   "Engine",
   "In The Aeroplane Over The Sea",
   "Jeff's Walking Wall of Beards explanation",
   "Mother"
  ],
  "links": []
 },
 {
  "date": "2010-05-06",
  "year": 2010,
  "venue": "Le Poisson Rouge",
  "city": "New York, NY",
  "format": "video clips",
  "source": "audience",
  "quality": "varies",
  "length": "(various clips)",
  "lineage": null,
  "no_recording": false,
  "notes": "Jeff Mangum played a 5-song set at a benefit show for Chris Knox in NYC. While a complete recording hasn't popped up yet, much of the show is available in clips on YouTube. The show was professionally recorded, with plans for a radio broadcast at a later date. Unfortunately, this hasn't happened, with rumors that Jeff changed his mind about allowing it.",
  "setlist": [
   "Oh Comely",
   "A Baby for Pree",
   "Two-Headed Boy Pt 2",
   "In the Aeroplane Over the Sea",
   "Engine"
  ],
  "links": []
 },
 {
  "date": "2010-12-05",
  "year": 2010,
  "venue": "Schoolhouse",
  "city": "New York, NY",
  "format": "audio",
  "source": "audience",
  "quality": "good",
  "length": "",
  "lineage": null,
  "no_recording": false,
  "notes": "Jeff played a surprise set of 10 NMH songs at a small venue called The Schoolhouse in Brooklyn, NY for a crowd of about 75. You can find the last half of the set online (link). Unfortunately, since the person who posted these showed up halfway through the set, a recording of the first half hasn't popped up online yet.",
  "setlist": [
   "Oh Comely",
   "In the Aeroplane Over the Sea",
   "Gardenhead",
   "Engine",
   "Ghost",
   "King of Carrot Flowers Pt. 1-3",
   "Song Against Sex",
   "Naomi",
   "Two Headed Boy",
   "Two Headed Boy Pt. 2"
  ],
  "links": []
 }
];
